const TOOL_ALIASES = {
  "cli-mcp-server_run_command": "run_command",
  "vgo-music": "run_command",
  "vgo_music": "run_command",
  "vgomusic": "run_command",
  "shell_command": "run_command",
  "bash": "run_command",
  "powershell": "run_command",
  "exec": "run_command",
  "execute": "run_command",
  copy: "copy_file",
  move: "move_file",
  rename: "rename_file",
  mkdir: "make_dir",
  create_directory: "make_dir",
  create_dir: "make_dir",
  rm: "delete_file",
  remove_file: "delete_file",
  rmdir: "delete_dir",
  remove_dir: "delete_dir",
  ls: "list_dir",
  dir: "list_dir",
  cat: "read_file",
  Read: "read_file",
  ReadFile: "read_file",
  Readfile: "read_file",
  read: "read_file",
  Glob: "search_code",
  glob: "search_code",
  Grep: "search_code",
  grep: "search_code",
  search: "search_code",
  Write: "write_file",
  write: "write_file",
  Edit: "str_replace",
  edit: "str_replace",
  ListFiles: "list_dir",
  list_files: "list_dir",
  LS: "list_dir",
  ls: "list_dir",
  find: "search_code",
  Bash: "run_command",
  bash: "run_command",
  OPEN_PATH: "open_path",
  open_path: "open_path",
  open: "open_path",
  browse: "fetch_web",
  get_url: "fetch_web",
  http_get: "fetch_web",
  transcribe: "transcribe_media",
  speech_to_text: "transcribe_media",
  WRITE_FILE: "write_file",
  write_file: "write_file",
  str_replace: "str_replace",
  StrReplace: "str_replace",
  Append: "append_file",
  append_file: "append_file",
  LIST_DIR: "list_dir",
  list_dir: "list_dir"
};

function normalizeToolName(name = "") {
  const raw = String(name || "").trim();
  const lowered = raw.toLowerCase();
  return TOOL_ALIASES[raw] || TOOL_ALIASES[lowered] || raw;
}

module.exports = { TOOL_ALIASES, normalizeToolName };
