const fs=require('fs');
let src=fs.readFileSync('electron/core/vgoRemoteAdapter.js','utf8');
const si=src.indexOf('async function runLocalPrompt(');
const ei=src.indexOf('\nasync function runPrompt(');
const newFn=[];
newFn.push('async function runLocalPrompt({workspace,sessionId,prompt,settings,history,sessionMeta,attachments=[],onEvent}) {');
newFn.push('  const remote=settings&&settings.remote||{};');
newFn.push('  const normalizedModelId=normalizeRemoteModelId(remote.model);');
newFn.push('  const endpointPlan=resolveLocalProviderEndpoint(baseUrl,remote.provider);');
newFn.push('  const detectedSkills=skillRegistry.detectRelevantSkills(prompt);');
newFn.push('  const activeSkills=resolveSkillRequiredInspectionPaths(detectedSkills,workspace);');
newFn.push('  const skillPreflightNudge=buildSkillPreflightNudge(activeSkills);');
newFn.push('  const skillWorkflowNudge=skillRegistry.buildSkillWorkflowNudge(activeSkills);');
newFn.push('  const systemPrompt=buildSafeSystemPrompt(settings,sessionMeta,activeSkills);');
newFn.push('  const authHeader=resolveAuthorizationHeaderValue(remote,endpointPlan.requestUrl);');
newFn.push('  const emit=(ev)=>emitEvent(onEvent,[],ev);');
newFn.push('  // sendRequest: wraps the HTTP call, returns {text, toolCalls}');
newFn.push('  const sendRequest=async(messages)=>{');
newFn.push('      ?JSON.stringify({model:normalizedModelId,messages,stream:false})');
newFn.push('      :JSON.stringify({model:normalizedModelId,systemPrompt,workspace,sessionId,prompt:finalPrompt,history});');
